# Generated by Django 5.2.15 on 2026-06-19 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('sex', models.CharField(choices=[('V', 'Varón'), ('M', 'Mujer')], max_length=1, verbose_name='Sexo')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Edad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('sex__in', ['V', 'M'])), name='patient_sex_valid')],
            },
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_number', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='N° de acceso')),
                ('register_date', models.DateField(verbose_name='Fecha de registro')),
                ('register_time', models.TimeField(verbose_name='Hora de registro')),
                ('exposure_date', models.DateField(verbose_name='Fecha de exposición')),
                ('exposure_time', models.TimeField(verbose_name='Hora de exposición')),
                ('body_part', models.CharField(blank=True, max_length=100, verbose_name='Parte del cuerpo')),
                ('referring_physician', models.CharField(max_length=200, verbose_name='Médico referente')),
                ('performing_physician', models.CharField(max_length=200, verbose_name='Médico ejecutor')),
                ('image_width', models.PositiveIntegerField(verbose_name='Ancho (px)')),
                ('image_height', models.PositiveIntegerField(verbose_name='Alto (px)')),
                ('bits_allocated', models.PositiveSmallIntegerField(verbose_name='Bits asignados')),
                ('bits_stored', models.PositiveSmallIntegerField(verbose_name='Bits usados')),
                ('pdf', models.FileField(upload_to='studies/%Y/%m/', verbose_name='PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='studies', to='studies.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Estudio',
                'verbose_name_plural': 'Estudios',
                'ordering': ['-exposure_date', '-exposure_time'],
                'constraints': [models.CheckConstraint(condition=models.Q(('bits_stored__lte', models.F('bits_allocated'))), name='study_bits_stored_le_allocated')],
            },
        ),
    ]
