# Generated by Django 5.2.15 on 2026-06-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='study',
            constraint=models.CheckConstraint(condition=models.Q(('exposure_date__lte', models.F('register_date'))), name='study_exposure_before_register'),
        ),
    ]
