# Generated by Django 5.2.15 on 2026-06-19 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_study_study_exposure_before_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='pdf',
        ),
        migrations.CreateModel(
            name='StudyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='studies/%Y/%m/', verbose_name='PDF')),
                ('description', models.CharField(blank=True, help_text='Opcional: vista, secuencia o nota del archivo.', max_length=200, verbose_name='Descripción')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='studies.study', verbose_name='Estudio')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
