# Generated by Django 5.2.15 on 2026-06-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0003_remove_study_pdf_studydocument'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='patient',
            name='patient_sex_valid',
        ),
        migrations.RemoveField(
            model_name='study',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='study',
            name='image_width',
        ),
        migrations.RemoveField(
            model_name='studydocument',
            name='pdf',
        ),
        migrations.AddField(
            model_name='studydocument',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Alto (px)'),
        ),
        migrations.AddField(
            model_name='studydocument',
            name='image',
            field=models.ImageField(default='', height_field='height', upload_to='studies/%Y/%m/', verbose_name='Imagen JPG', width_field='width'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studydocument',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ancho (px)'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(blank=True, choices=[('V', 'Varón'), ('M', 'Mujer')], max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='study',
            name='bits_allocated',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Bits asignados'),
        ),
        migrations.AlterField(
            model_name='study',
            name='bits_stored',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Bits usados'),
        ),
        migrations.AlterField(
            model_name='study',
            name='exposure_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de exposición'),
        ),
        migrations.AlterField(
            model_name='study',
            name='exposure_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de exposición'),
        ),
        migrations.AlterField(
            model_name='study',
            name='performing_physician',
            field=models.CharField(blank=True, max_length=200, verbose_name='Médico ejecutor'),
        ),
        migrations.AlterField(
            model_name='study',
            name='referring_physician',
            field=models.CharField(blank=True, max_length=200, verbose_name='Médico referente'),
        ),
        migrations.AlterField(
            model_name='study',
            name='register_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='study',
            name='register_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de registro'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.CheckConstraint(condition=models.Q(('sex__in', ['V', 'M', ''])), name='patient_sex_valid'),
        ),
    ]
