# Generated by Django 5.2.15 on 2026-06-22 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0004_remove_patient_patient_sex_valid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Parte del cuerpo',
                'verbose_name_plural': 'Partes del cuerpo',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='study',
            name='body_part',
        ),
        migrations.AddField(
            model_name='studydocument',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='studydocument',
            name='body_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='studies.bodypart', verbose_name='Parte del cuerpo'),
        ),
    ]
