# Generated by Django 5.2.15 on 2026-06-22 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0005_bodypart_remove_study_body_part_studydocument_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studydocument',
            name='description',
        ),
    ]
